name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
    build-artifact:
        name: Build
        runs-on: ubuntu-latest
        container: devkitpro/devkita64

        steps:
        - name: Check for dockerenv file
          run: echo $DEVKITPRO
            
        - name: checkout repository
          uses: actions/checkout@master
          with:
            submodules: recursive
            
        - name: setup environment
          run: sudo bash setup.bash
        
        - name: build
          run: sudo bash build.bash

        - name: upload raw
          uses: actions/upload-artifact@master
          with:
            name: raw
            path: raw.zip
